server:
  tomcat:
    uri-encoding: UTF-8
shaoming:
  username: 邵明
  age: 22

spring:
  profiles:
    active: dev
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver  #引入sql性能分析插件p6spy后 需要更换驱动
#    url: jdbc:mysql:///world   #引入sql性能分析插件p6spy后 需要更换url
    url: jdbc:p6spy:mysql://localhost:3306/world
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: adminadmin


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

    #日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #逻辑删除设置
  global-config:
    db-config:
      #logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加@TableLogic在实体类字段上)
      logic-delete-value: 1
      logic-not-delete-value: 0

