server:
  tomcat:
    uri-encoding: UTF-8
shaoming:
  username: 邵明
  age: 22

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///world
    username: root
    password: adminadmin

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
